### ISSUE TITLE
[ADDB] Add function name resolution based on function address

### ISSUE THREAD

**Issue by maximalezhin** [Seagate/cortx-rgw#193]
Two reasons:
1. I had no clue about m0_ptr_wrap() and function name resolving. Thanks @nikitadanilov for pointing the right direction. S3server code implements the same function <-> idx map as implemented here, and just reused the code.
2. @andriytk Does RGW build system generate shared (or static) library? If yes, what is it? Can libbfd() deal with C++ symbols? I suggest to take function address-name resolution as another ticket (and PR)

_Originally posted by @maximalezhin in https://github.com/Seagate/cortx-rgw/pull/142#discussion_r864827692_

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31238. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by andriytk** [comment]
@maximalezhin please edit and clarify the description of this issue. In its current form, it looks like cut out from another context.

**Comment by cortx-admin** [comment]
> Amit Kapil commented in Jira Server:

Should this be converted as story? [~721080] and [~520414]

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
