### ISSUE TITLE
Optimisation: cleanup bucket multipart index in background

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-rgw#69]
Bucket multipart index stores the records for the ongoing multipart uploads. Currently, the records are deleted when the upload is completed. Consider deferring this cleanup in the background. For example, from GC.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-28853. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by hessio** [comment]
Hi @andriytk is this issue still relevant?

**Comment by andriytk** [comment]
Yes.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
